# Generated by Django 5.0.1 on 2024-01-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('numero_cartao', models.CharField(max_length=20)),
                ('nome_do_cartao', models.CharField(max_length=18)),
                ('validade', models.CharField(max_length=18)),
                ('cvv', models.CharField(max_length=18)),
            ],
        ),
    ]
